### ISSUE TITLE
Immunization strategy example

### ISSUE THREAD

**Issue by vgoliber** [dwave-examples/template#14]
**Link to your repo**

My repository is currently private. I can add anyone you need me to as a contributor to review.

**Environment**
 - Operating system: macOS 10.15
 - Python version: 3.8.3

**Additional information**

Title: Immunization Strategy

**Comment by arcondello** [comment]
Can you add a link? Only those with access will be able to view it and later if you make it public we can refer back to it.

**Comment by vgoliber** [comment]
https://github.com/vgoliber/immunization-strategy
