### ISSUE TITLE
New example to contribute

### ISSUE THREAD

**Issue by vgoliber** [dwave-examples/template#16]
**Link to your repo**

https://github.com/vgoliber/airline-hubs/

Topic: Choosing airports for airline hubs

A challenging optimization problem in the airline industry is determining which airports should be hub locations for an airline.

**Comment by vgoliber** [comment]
@hhtong I added you to the repo so that you can review

**Comment by hhtong** [comment]
Sounds good, I'll try to go through it by the end of this week

**Comment by hhtong** [comment]
Closing. Airline hubs example can be found here: https://github.com/dwave-examples/airline-hubs
