### ISSUE TITLE
Please add Crop Rotation example to D-Wave examples

### ISSUE THREAD

**Issue by seatim** [dwave-examples/template#17]
**Link to your repo**

https://github.com/seatim/crop_rotation

**Environment**

 - Operating system: tested on macOS 10.15 + Ubuntu 18.04
 - Python version: tested on 3.8; should work with 3.6+

**Additional information**

None

**Comment by hhtong** [comment]
Crop rotation example has been added to dwave-examples: https://github.com/dwave-examples/crop-rotation
