### ISSUE TITLE
 Line-up-optimization

### ISSUE THREAD

**Issue by spdtek** [dwave-examples/template#19]
**Link to your repo**

https://github.com/spdtek/Line-up-optimization

**Environment**
 - Operating system: [Windows 10]
 - Python version: [e.g., 3.7.0]

**Comment by spdtek** [comment]
Hi,
We would like to contribute with this example that shows a simple demo for optimizing the line-up of a soccer team.
Regards
Aitzol

**Comment by hhtong** [comment]
Hi @spdtek, thanks for your contribution! I took a look today and it seems like `players.csv` is missing from your repository (unless the user is expected to provide the data). Would it be possible for you to add this data file in? 

Once that’s done, we’ll do some testing on our end and if everything is working, we’d love to fork your repository on dwave-examples. There may be some minor adjustments we’d like to propose, but that’s something we can do on our fork and possibly submit as a PR to you at a later time.

Please let us know if this sounds good and if you have any questions/concerns!

**Comment by spdtek** [comment]
Thanks Heidi,

I 've just uploaded the players.csv file... please let me know if something
else is missing or any other adjustment is required.

Regards

Aitzol

**Comment by hhtong** [comment]
Thanks Aitzol! Your example can be found here: https://github.com/dwave-examples/Line-up-optimization
