### ISSUE TITLE
-

### ISSUE THREAD

**Issue by AngelikiMitselou9** [dwave-examples/template#20]
**Link to your repo**

Include a link to the repo you want to contribute to dwave-examples.

**Environment**
 - Operating system: [e.g., macOS 10.15]
 - Python version: [e.g., 3.9.0]

**Additional information**

Add any information that is not included in your example's README.

Before submitting, we encourage you to take a look at our contribution
guidelines: https://github.com/dwave-examples/template/blob/master/CONTRIBUTING.md.

**Comment by randomir** [comment]
@AngelikiMitselou9, is there a repo/example you'd like to contribute? If so, can you please post a link to it? If not, feel free to close the issue.
