### ISSUE TITLE
We have an example we would like to contribute

### ISSUE THREAD

**Issue by pgora** [dwave-examples/template#7]
**Description**

We develop algorithms for solving the Capacitated Vehicle Routing Problem (CVRP) using D-Wave’s solvers. It is an open source project and results of our experiments were summarized in a paper “New hybrid quantum annealing algorithms for solving Vehicle Routing Problem” accepted for the ICCS conference (https://link.springer.com/chapter/10.1007/978-3-030-50433-5_42).

**How to run the example**

The README is available in our current repository: https://github.com/xBorox1/D-Wave-2, e.g., you can just run python3 SolutionPartitioningSolver.py to see an example.

**Link to your repo**

https://github.com/xBorox1/D-Wave-2

**Environment**
 - Python version: 3.7.0
 - Ocean version: 2.1

**Additional information**

License: Apache 2.0

**Comment by hhtong** [comment]
Hi @pgora, thanks for your contribution and sorry for the long wait! This is really cool work that you guys have done, and we would like to fork your repository on dwave-examples. 

We are also hoping to update your contribution to use the latest version of dwave-ocean-sdk and add some basic smoke tests to ensure that everything is running as it should. This is something we can do on our fork and may later submit a pull request to you. 

Please let us know if this sounds good and if you have any questions or concerns.

**Comment by pgora** [comment]
Hello! Yes, it looks goods, thanks for this opportunity.

**Comment by hhtong** [comment]
Link to example: https://github.com/dwave-examples/D-Wave-VRP

**Comment by pgora** [comment]
Hello!

I just wanted to let you know that we are planning to update the repository
to use the latest version of Ocean. Let me know if this is OK with you and
if there are any things we should consider before we proceed.

Best regards
--
Paweł Gora
(+48) 507 982 292
www <http://www.mimuw.edu.pl/~pawelg> | LinkedIn
<https://www.linkedin.com/in/pawelgora>

**Comment by randomir** [comment]
That would be great, please do! :slightly_smiling_face: 

The only thing to consider is adding [our `devcontainer.json`](https://github.com/dwave-examples/template/blob/master/.devcontainer/devcontainer.json) that we use on our examples, so it can easily be run from GitHub Codespaces.

**Comment by pgora** [comment]
OK, thanks!

Should we create another branch in the same repository and then submit a
pull request, or do you prefer another way to proceed?

Best regards
--
Paweł Gora
(+48) 507 982 292
www <http://www.mimuw.edu.pl/~pawelg> | LinkedIn
<https://www.linkedin.com/in/pawelgora>

**Comment by thisac** [comment]
Hi @pgora. You can create a new branch in your original repository (https://github.com/xBorox1/D-Wave-2) (or just update the main branch there, if you prefer) and then create a PR for the example on our organization (https://github.com/dwave-examples/D-Wave-VRP). Just make sure that it's up to date with our fork first.

If you prefer you could also create a completely new fork but I don't think that's really necessary here.
